# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easyeditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_dir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dir.setGeometry(QtCore.QRect(20, 10, 151, 41))
        self.btn_dir.setObjectName("btn_dir")
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setGeometry(QtCore.QRect(210, 490, 131, 41))
        self.btn_left.setObjectName("btn_left")
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setGeometry(QtCore.QRect(360, 490, 131, 41))
        self.btn_right.setObjectName("btn_right")
        self.btn_sharp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sharp.setGeometry(QtCore.QRect(660, 490, 131, 41))
        self.btn_sharp.setObjectName("btn_sharp")
        self.btn_mirror = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mirror.setGeometry(QtCore.QRect(510, 490, 131, 41))
        self.btn_mirror.setObjectName("btn_mirror")
        self.btn_bw = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bw.setGeometry(QtCore.QRect(810, 490, 131, 41))
        self.btn_bw.setObjectName("btn_bw")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 60, 151, 471))
        self.listWidget.setObjectName("listWidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(210, 30, 731, 381))
        self.image.setObjectName("image")
        self.btn_emboss = QtWidgets.QPushButton(self.centralwidget)
        self.btn_emboss.setGeometry(QtCore.QRect(810, 440, 131, 41))
        self.btn_emboss.setObjectName("btn_emboss")
        self.btn_crop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_crop.setGeometry(QtCore.QRect(510, 440, 131, 41))
        self.btn_crop.setObjectName("btn_crop")
        self.btn_contour = QtWidgets.QPushButton(self.centralwidget)
        self.btn_contour.setGeometry(QtCore.QRect(660, 440, 131, 41))
        self.btn_contour.setObjectName("btn_contour")
        self.btn_flip = QtWidgets.QPushButton(self.centralwidget)
        self.btn_flip.setGeometry(QtCore.QRect(210, 440, 131, 41))
        self.btn_flip.setObjectName("btn_flip")
        self.btn_blur = QtWidgets.QPushButton(self.centralwidget)
        self.btn_blur.setGeometry(QtCore.QRect(360, 440, 131, 41))
        self.btn_blur.setObjectName("btn_blur")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 977, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Image Editor", "Image Editor"))
        self.btn_dir.setText(_translate("MainWindow", "Папка"))
        self.btn_left.setText(_translate("MainWindow", "Вліво"))
        self.btn_right.setText(_translate("MainWindow", "Вправо"))
        self.btn_sharp.setText(_translate("MainWindow", "Різкість"))
        self.btn_mirror.setText(_translate("MainWindow", "Дзеркало"))
        self.btn_bw.setText(_translate("MainWindow", "Ч/Б"))
        self.image.setText(_translate("MainWindow", ""))
        self.btn_emboss.setText(_translate("MainWindow", "Стиснення"))
        self.btn_crop.setText(_translate("MainWindow", "Обрізання"))
        self.btn_contour.setText(_translate("MainWindow", "Контур"))
        self.btn_blur.setText(_translate("MainWindow", "Розмиття"))
        self.btn_flip.setText(_translate("MainWindow", "Перевернути"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())